[package]
name = "config"
version = "0.0.0"
authors = ["Erlend Hofstad Langseth <3rlendhl@gmail.com>", "Kevin Robert Stravers <macocio@gmail.com>"]
edition = "2018"

[lib]
name = "config"
path = "lib.rs"

[dependencies]
failure = "0.1.5"
ron = "0.5.1"
serde = "1.0.90"
